version: '3.8'

services:
  app:
    build: .
    container_name: questionnaireForm20150521
    volumes:
      - .\app:/usr/src/app
    environment:
      VITE_ENV: $VITE_ENV
      LANG: C.UTF-8
      TZ: Asia/Tokyo
    ports:
      - ${FRONTEND_PORT}:3000
    tty: true
    stdin_open: true
    # command: bash -c "npm run dev"
    command: bash
